version: '3.8'

services:
  rtsp-server:
    image: aler9/rtsp-simple-server
    ports:
      - "8554:8554"
    volumes:
      - ./rtsp-config:/rtsp-simple-server
    networks:
      - streaming_network

  rtap-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"  # Zmieniony port
    environment:
      - RTSP_URL=rtsp://rtsp-server:8554/stream
      - RTAP_PORT=9000  # Ustawienie portu przez zmienną środowiskową
      - RTAP_HOST=0.0.0.0
    depends_on:
      - rtsp-server
    networks:
      - streaming_network

networks:
  streaming_network:
    driver: bridge